plugins:
  fast_quote_enabled:
    default: true
    client: true
  fast_quote_post_location_threshold:
    default: 3
    client: true
  fast_quote_remove_prior_quotes:
    default: true
    client: true
  fast_quote_remove_links:
    default: true
    client: true
